ARG PRETALX_BASE_IMAGE=docker.io/library/pretalx/pretalx
ARG PRETALX_BASE_TAG=2024.3.0

FROM ${PRETALX_BASE_IMAGE}:${PRETALX_BASE_TAG}
RUN pip3 install -U --user prtx-faq \
                            pretalx-pages \
                            pretalx-public-voting
