
ARG PRETALX_BASE_IMAGE=docker.io/library/pretalx/pretalx
ARG PRETALX_BASE_TAG=2024.1.0

FROM ${PRETALX_BASE_IMAGE}:${PRETALX_BASE_TAG} AS system

USER pretalx
RUN pip3 install -U prtx-faq \
                    pretalx-pages \
                    pretalx-public-voting

USER root
